import axios from 'axios';

const token = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiZHUuZnN0ZWMucnUiLCJhdWQiOnsiMCI6ImFwaVJlYWRPbmx5IiwiMiI6ImFwaV9nZXQifSwiZXhwIjoxNjc4NzAzNzU3LCJpZCI6IjQ3IiwianRpIjoiZGU5N2QzNWM0NDM4MmRiOWFiZjY4N2ZkMDlmOTViMDQ0NmQyZGIyNDhiNTM3ZjhhMDUzMTFiZDc3ODFhOGFjNzJhOGQxNzg3MjVkNzNhNjk1NGJmMjdjMGI0ODIxZDM0Zjg2YWFjNmU2NWEwYjYwNTY2OGJhMmRiN2Y3MDU0MTMiLCJpYXQiOjE2Nzg3MDE5NTd9.HmnnJD0oTEFiJRztM0S3FJxEtYzdY5OnGXRoLwimIwl6Fzg957Ypmqc11t_hf6VTFxJ14NBsMO5b-mGzQTC6rA'
export const api =  axios.create({
  headers: {
    Authorization: `Bearer ${token}`
  }
});



